dist: focal
language: node_js

node_js:
  - "stable"

cache:
  yarn: true
  pip: true
  directories:
    - node_modules

branches:
  only:
    - master

before_script:
  - pip install openwisp-utils[qa]

script:
  - ./run-qa-checks
  - yarn test

after_success:
  - yarn coveralls

notifications:
  # will post a summary as a comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never
