language: node_js

node_js:
  - "stable"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

script:
  - yarn setup
  - yarn lint
  - yarn test

after_success:
  - yarn coveralls

notifications:
  # will post a summary as a comment on github in case of failure
  webhooks: https://www.travisbuddy.com/
  on_success: never
